# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Rerun Failed Workflow
on:
  pull_request_target:
    types: [labeled]

permissions:
  actions: write
  checks: read
  pull-requests: write

jobs:
  rerun:
    name: Rerun Failed CI
    if: github.event.label.name == 'CI:Rerun'
    runs-on: ubuntu-latest
    steps:
      - name: Rerun failed GitHub actions
        uses: actions/github-script@v7
        with:
          script: |
            let rerun = new Set();

            const check_runs = (await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            })).data.check_runs;

            // GitHub creates a check run for each *job*, so we need to extract run id and dedup.
            for (let run of check_runs) {
              if (run.app.slug != 'github-actions') continue;
              if (run.conclusion != 'failure') continue;
              let match = /runs\/([0-9]+)/.exec(run.html_url);
              if (!match) continue;
              rerun.add(match[1]);
            }

            let run;
            try {
              for (run of rerun) {
                await github.rest.actions.reRunWorkflowFailedJobs({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run,
                });
              }
            } catch (err) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Error rerunning failed job of run ${run}: ${err}`,
              });
            }

            // Remove label once failed job retriggered.
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'CI:Rerun',
            });
